### ISSUE TITLE
Question. Only on light theme

### ISSUE THREAD

**Issue by Vctrsnts** [andrewhwanpark/minimal-bootstrap-blog#1]
Hi,

The firts, thanks for your theme, but I have a question.

Is possible only use this theme with light theme? Disable de dark theme?

How?

Thanks a lot

**Comment by jawadnassar** [comment]
under `_layouts/default.html` change line 10 to

`<meta name="color-scheme" content="light only" />`

**Comment by Vctrsnts** [comment]
Thanks a lot.

**Comment by jawadnassar** [comment]
sure thing! please note that some browsers might not be compatible, you can always remove all dark mode supporting CSS/html code.. learn more about it via  https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by Vctrsnts** [comment]
Thanks a lot. Im testing if working.

And if not working, not problem.

Thanks.
